# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'parkzone' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for parkzone
  pod 'GoogleMaps'
end
